# Your name and what you do
name: Nick Sawinyh
bio: Growth Focused Product Manager

description: Growth focused Product Manager for Saas/Web/Crypto projects with remote first teams. Currently I'm interested in Blockchain oportunities.

# Profile picture
picture: assets/images/sawinyh.jpg

# your url: http://USERNAME.github.io
url: https://sneg55.github.io/sneg55

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: sawinyh
linkedin: sawinyh
github: sneg55
email: nsawinyh@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
medium: sawinyh
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - SEO
    - PPC
    - SMM
    - HTML, CSS
    - Agile, Scrum
    - Git

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    2Miners.com:
        name: 2Miners.com
        description: Multi-coin cryptocurrency mining pool.
        url: https://2miners.com
    2Masternodes.com:
        name: 2Masternodes.com
        description: First fully automated and transparent shared-masternode hosting.
        url: https://2masternodes.com
    Seomator:
        name: Seomator
        description: Saas SEO Audit tool for SEO professionals
        url: https://seomator.com
    Curatedseotools:
        name: Curatedseotools
        description: Best SEO Tools Stash
        url: https://curatedseotools.com
# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
