# Your name and what you do
name: Nick Sawinyh
bio: Growth Focused Project Manager

description: Growth focused Project/Product Manager for Saas/Web/Crypto projects with Remote Teams. Currently I'm interested in Blockchain oportunities.

# Profile picture
picture: assets/images/sawinyh.jpg

# your url: http://USERNAME.github.io
url: https://sneg55.github.io/sneg55

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: sawinyh
linkedin: sawinyh
github: sneg55
email: nsawinyh@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - SEO
    - PPC
    - SMM
    - HTML, CSS
    - Agile, Scrum
    - Git

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Callisto Network:
        name: Callisto Network
        description: Callisto Network is a blockchain platform with its own cryptocurrency (CLO) that is based on Ethereum protocol, so any Callisto improvements can be applied to Ethereum Classic. Callisto is NOT a testnet or a hardfork of Ethereum Classic. Callisto Network is developed by Ethereum Commonwealth, one of three ETC development teams.
        url: https://callisto.network/
    2Miners.com:
        name: 2Miners.com
        description: Altcoin's Mining Pool
        url: https://2miners.com
    Seomator:
        name: Seomator
        description: Saas SEO Audit tool for SEO professionals
        url: https://seomator.com


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
